{
 "title": "Power consumption analysis",
 "time": { "from": "2017-01-07T01:04:14.377Z", "to": "2017-01-09T01:00:25.445Z" },
 "panels": [
  {
   "title": "Average power consumption statistics in weekend ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: 2017-01-07T01:54:12.821Z, stop: 2017-01-08T23:54:12.821Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\" or r[\"_field\"] == \"PowerConsumption_Zones_AVG\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "One month power consumption in 3 zones",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: 2017-01-01T01:54:12.821Z, stop: 2017-01-30T23:54:12.821Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power consumption in weekend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: 2017-01-07T01:54:12.821Z, stop: 2017-01-08T23:54:12.821Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\" or r[\"_field\"] == \"PowerConsumption_Zones_AVG\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Average power consumption is one day ",
   "type": "candlestick",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: 2017-01-07T01:54:12.821Z, stop: 2017-01-07T23:54:12.821Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zones_AVG\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}