{
 "title": "PowerConsumption",
 "time": { "from": "2017-01-02T14:26:53.786Z", "to": "2017-01-07T05:41:52.653Z" },
 "panels": [
  {
   "title": "Daily measurements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily max windspeed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"WindSpeed\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> yield(name: \"max\")"
      }
     ]
    },
    {
     "title": "daily mean diffuse flows and general diffuse flows",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"GeneralDiffuseFlows\" or r[\"_field\"] == \"DiffuseFlows\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Daily average temperature",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Daily average windspeed",
     "type": "stat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"WindSpeed\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Daily average humidity",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity\")\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Daily comparation of 3 zones",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"processedPowerConsumptionData\" and\n    r._field == \"PowerConsumption_Zone1\"  or r._field == \"PowerConsumption_Zone2\" or r._field == \"PowerConsumption_Zone3\"\n  )\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)"
      }
     ]
    }
   ]
  },
  {
   "title": "Weekly report",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Humidity  of 3 zones",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity\" or r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\")\n  |> aggregateWindow(every: 7d, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
      }
     ]
    },
    {
     "title": "Humidity  classification",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"processedPowerConsumptionData\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Humidity_Classification\")\n  |> aggregateWindow(every: v.windowPeriod, fn: min, createEmpty: false)\n  |> yield(name: \"min\")"
      }
     ]
    },
    {
     "title": "Weekly humidity ",
     "type": "timeseries",
     "description": "Humidity level with zones",
     "gridPos": { "h": 8, "w": 12, "x": 7, "y": 9 },
     "targets": [
      {
       "query": "from(bucket: \"powerConsumption\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"processedPowerConsumptionData\" and r._field == \"Humidity\")\n  |> window(every: 1w)"
      }
     ]
    }
   ]
  }
 ]
}