{
 "title": "Power Consumption Report",
 "time": { "from": "2017-01-17T20:35:15.000Z", "to": "2017-03-20T16:34:44.000Z" },
 "panels": [
  {
   "title": "Average Power Consumption",
   "type": "stat",
   "description": "Average power zone of all three zones",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r._field == \"PowerConsumption_Zone1\" or r._field == \"PowerConsumption_Zone2\" or  r._field == \"PowerConsumption_Zone3\")\r\n  |> highestAverage(n:10, groupColumns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Power Consumption per Zone",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone3\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Consumptions  Weakly",
   "type": "timeseries",
   "description": "Visualize different Zones",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\")\r\n  |> aggregateWindow(every: 7d, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\" or r[\"_field\"] == \"DiffuseFlows\" or r[\"_field\"] == \"GeneralDiffuseFlows\" or r[\"_field\"] == \"Humidity\" or r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"WindSpeed\")\r\n  |> aggregateWindow(every: 7d, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power Consumption Daily",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\")\r\n  |> aggregateWindow(every: 24h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Zones",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\r\nfrom(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"PowerConsumption_Zone3\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone1\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Humidity, Temperature and WindSpeed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"WindSpeed\" or r[\"_field\"] == \"Humidity\")\r\n  |> aggregateWindow(every: 7d, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Power consumption Zone and Temperature",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\")\r\n  |> aggregateWindow(every: 7d, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Time Series",
   "type": "timeseries",
   "description": "Time series for all features, Daily",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"powerConsumption\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"powerConsumptionData\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperature\" or r[\"_field\"] == \"WindSpeed\" or r[\"_field\"] == \"Humidity\" or r[\"_field\"] == \"DiffuseFlows\" or r[\"_field\"] == \"GeneralDiffuseFlows\" or r[\"_field\"] == \"PowerConsumption_Zone1\" or r[\"_field\"] == \"PowerConsumption_Zone2\" or r[\"_field\"] == \"PowerConsumption_Zone3\")\r\n  |> aggregateWindow(every: 7d, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}